SQLTransactionBackend.h: Avoid invalid application of 'sizeof' to incomplete type with gcc
/home/griffinp/oe/rocko/build-rpb-wayland/tmp-rpb_wayland-glibc/work/aarch64-linaro-linux/chromium-ozone-wayland/65.0.3315.0.r527534.igalia.1-r0/recipe-sysroot/usr/include/c++/7.1.1/bits/unique_ptr.h: In instantiation of 'void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = blink::SQLErrorData]':
/home/griffinp/oe/rocko/build-rpb-wayland/tmp-rpb_wayland-glibc/work/aarch64-linaro-linux/chromium-ozone-wayland/65.0.3315.0.r527534.igalia.1-r0/recipe-sysroot/usr/include/c++/7.1.1/bits/unique_ptr.h:268:17:   required from 'std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = blink::SQLErrorData; _Dp = std::default_delete<blink::SQLErrorData>]'
../../third_party/WebKit/Source/modules/webdatabase/SQLStatementBackend.h:45:7:   required from 'void blink::GarbageCollectedFinalized<T>::FinalizeGarbageCollectedObject() [with T = blink::SQLStatementBackend]'
../../third_party/WebKit/Source/platform/heap/GCInfo.h:35:5:   required from 'static void blink::FinalizerTraitImpl<T, true>::Finalize(void*) [with T = blink::SQLStatementBackend]'
../../third_party/WebKit/Source/platform/heap/GCInfo.h:61:58:   required from 'static void blink::FinalizerTrait<T>::Finalize(void*) [with T = blink::SQLStatementBackend]'
../../third_party/WebKit/Source/platform/heap/GCInfo.h:195:25:   required from 'static size_t blink::GCInfoAtBaseType<T>::Index() [with T = blink::SQLStatementBackend; size_t = long unsigned int]'
../../third_party/WebKit/Source/platform/heap/GCInfo.h:231:78:   [ skipping 7 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
../../third_party/WebKit/Source/platform/heap/Persistent.h:442:36:   required from 'blink::CrossThreadPersistent<T>::CrossThreadPersistent() [with T = blink::SQLStatementBackend]'
/home/griffinp/oe/rocko/build-rpb-wayland/tmp-rpb_wayland-glibc/work/aarch64-linaro-linux/chromium-ozone-wayland/65.0.3315.0.r527534.igalia.1-r0/recipe-sysroot/usr/include/c++/7.1.1/type_traits:1366:12:   required from 'struct std::is_trivially_constructible<blink::CrossThreadPersistent<blink::SQLStatementBackend> >'
/home/griffinp/oe/rocko/build-rpb-wayland/tmp-rpb_wayland-glibc/work/aarch64-linaro-linux/chromium-ozone-wayland/65.0.3315.0.r527534.igalia.1-r0/recipe-sysroot/usr/include/c++/7.1.1/type_traits:1373:12:   required from 'struct std::is_trivially_default_constructible<blink::CrossThreadPersistent<blink::SQLStatementBackend> >'
../../third_party/WebKit/Source/platform/wtf/VectorTraits.h:37:25:   required from 'constexpr const bool WTF::VectorTraitsBase<blink::CrossThreadPersistent<blink::SQLStatementBackend> >::kCanInitializeWithMemset'
../../third_party/WebKit/Source/platform/wtf/Deque.h:153:21:   required from 'class WTF::Deque<blink::CrossThreadPersistent<blink::SQLStatementBackend> >'
../../third_party/WebKit/Source/modules/webdatabase/SQLTransactionBackend.h:138:53:   required from here
/home/griffinp/oe/rocko/build-rpb-wayland/tmp-rpb_wayland-glibc/work/aarch64-linaro-linux/chromium-ozone-wayland/65.0.3315.0.r527534.igalia.1-r0/recipe-sysroot/usr/include/c++/7.1.1/bits/unique_ptr.h:76:22: error: invalid application of 'sizeof' to incomplete type 'blink::SQLErrorData'
  static_assert(sizeof(_Tp)>0,

Signed-off-by: Peter Griffin <peter.griffin@linaro.org>